version: '3'
services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_PASSWORD: devops
      POSTGRES_USER: pete
      POSTGRES_DB: foo
    ports:
      - "5432:5432"
    volumes:
      - ./misc/snapshot-prod-data.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: mattcul/assignment2app:1.0.0
    environment:
      PORT: 3001
      DB_HOSTNAME: db
      DB_PORT: 5432
      DB_USERNAME: pete
      DB_PASSWORD: devops
    ports:
      - "80:3001"
    depends_on:
      - db